name: Compile Golang
on: push
jobs:
  golang:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: go/sdp
      run: |
        go get -v -t -d ./...
  
    - name: Build
      working-directory: go/sdp
      run: go build -v .

    - name: Test
      working-directory: go/sdp
      run: go test -v ./...
