name: Generate Golang
on: push
jobs:
  golang:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate go code
      run: |
        protoc -I . *.proto --go_out /tmp
